### ISSUE TITLE
Items with quantity > 1 are added into the spreadsheet only once

### ISSUE THREAD

**Issue by gabrielKerekes** [vacuumlabs/eshop-api#20]
The count property has been forgotten during the migration to google sheets.

If you make an order containing the same item twice (by sending it twice in one message), alzabot shows the item twice and the price is also multiplied, however it will be included in the spreadsheet only once.

**Comment by fajzen** [comment]
fixed in https://github.com/vacuumlabs/eshop-api/pull/21
